---
# tasks file for nginx
- name: install nginx
  apt:
    name: "nginx"
    state: present

- name: change page
  template:
    src: index.j2
    dest: /var/www/html/index.nginx-debian.html
  notify: "reloader"
